services:
  - type: web
    name: pakajo
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    root: "/"
    rootDirectory: "."
    healthCheckPath: "/"
    autoDeploy: true
    env:
      - key: NODE_ENV
        value: production
